### ISSUE TITLE
Update API count for manual Solcast polls as well as scheduled polls

### ISSUE THREAD

**Issue by gcoan** [BJReplay/ha-solcast-solar#228] opened 2024-12-17 19:17 UTC
**Is your feature request related to a problem? Please describe.**
I am confused as to why "by design" the API count is not being updated when I make a manual Solcast update

**Describe the solution you'd like**
The sensor to show the total number of API calls, not just those auto-scheduled.

**Additional context**
Solcast 4.2.7

Set to auto update between sunset and sunrise with API limit set to 8, and a manually scheduled Solcast update in my own automation at 01:05.

I noticed that the APIs used, it only ever gets to 8 each day:
![image](https://github.com/user-attachments/assets/d6231958-1f46-4777-8186-cf95da599030)

I do think its confusing that there isn't a clear sensor that tells you how many API calls have been used in total.  I went down a rabbit hole of trying to debug why my auto scheduled updates were not occurring, finding out from the solar forecast sensor, it changes at 1am each night suggesting that the manual update is working OK.
![image](https://github.com/user-attachments/assets/25297d51-5eb0-403e-8dae-e2abc7dfad1b)

It was only when I checked the API call in the documentation did I find that this non-update of the count is by design.

I'd suggest that if you need to keep a count of how many auto-scheduled updates have been done that this be introduced as an attribute of the existing API count sensor, that way the sensor always shows the total number of API calls regardless of how they were initiated.  After all the manual updates are via the integration, its not as if I am consuming API calls via some independent method that the integration knows nothing about

**Comment by BJReplay** [comment] 2024-12-17 19:52
Has been discussed at length.

Will not be re-introduced. 

Hassle Solcast to return the API that allows us to know how many API calls have been used.

**Comment by autoSteve** [comment] 2024-12-18 00:26
I concur, @BJReplay.

We _could_ add an attribute to the API use entity not of the auto-update count, but rather the "true" API count in my opinion. That would result in minimal code change, but for almost no value.

I don't think we should do it.

We need an API call to get true usage. Scenario: integration uses API calls. Something else uses API calls from same account. Integration will get sad and confused.

The way the old API usage call was used had it occur on integration start. If a new one were made available the way that I would utilise it would probably be a call prior to each forecast update to check where usage is at.

All forecast update activity is logged at `INFO` level, indicating whether an update is auto or forced. A simple `grep` could filter for either or both types for debugging when things are occurring. Not exactly user-friendly, but it would verify that things are happening when they should happen. Automation traces also reveal execution.

<img width="533" alt="image" src="https://github.com/user-attachments/assets/4622694e-a277-4399-b2f3-e0952fe94f1a" />

**Comment by BJReplay** [comment] 2024-12-18 00:42
I'm going to close this.  The final nail in the coffin is survivability of integration upgrades, reloads, restarts and HA upgrades and restarts.  What we have now is a reasonable, best efforts attempt to spread the load across what you - the user - tell the integration is the available quota.  We don't know what you're doing outside of the integration that might use up the quota, or if you want to force an update for whatever reason and hang the quota for later in the UTC day.

**Closed by BJReplay** 2024-12-18 00:42 UTC
Labels: wontfix, read the readme

**Comment by gcoan** [comment] 2024-12-18 00:59
Guys I think you are missing the point.

I am not asking for you to guess how I am using the quota up by round the side calls to the Solcast API, I think what I am asking for is quite simple and reasonable.

1. Every single call via the integration (that is successful) updates the API count used.  Regardless of which mechanism is used, whether (a) totally manually scheduled API calls, (b) the auto retrieval API calls or (c) the manual retrieve **that uses the Solcast integration API** alongside the auto scheduled API calls

At the moment (a) and (b) increment the count but (c) doesn't and I see no logical reason for it.  If there is a logical reason please can we discuss it and not just dismiss the suggestion out of hand?

2. IF the auto schedule needs to count the number of auto schedule API calls to compare to the auto schedule limit (8 in my case) then I suggested this could be provided with this data as an attribute of the existing sensor so that this part of the code can continue without breaking and with minimal change

It looks to me to be a fairly simple request and potential code change that would mean that the API count provided is more all inclusive than it is at the moment.

To re-iterate, I am using the provided action: solcast_solar.force_update_forecasts not making a round the side API call direct to Solcast, just asking that this increments the API count already available.

Don't see how this has anything to do with integration restarts breaking the count or anything else.  A call is made via the integration, why not count it in the existing sensor?

**Comment by autoSteve** [comment] 2024-12-18 07:02
The logical reason is incorporating auto-update with the ability to lower the API limit to allow for outside-of-auto scheduled updates. The design decision was to not create another set of counters for auto-update to keep that scheduling as simple as could be. When auto-update is enabled think of the limit/used as `API limit` = "the limit of API calls that I want you to use for auto-update", and `API used` = "how many API calls has auto-update used". This will not match Solcast, because design decision.

Happy to discuss.

As a work-around, @gcoan how about the following:

1. Create a helper number.
2. Increment that helper number when the value of `sensor.solcast_pv_forecast_api_last_polled` changes. This entity is always updated on successful update completion regardless of force fetch or auto. If the fetch fails it is not updated.
3. Reset the helper to zero at UTC midnight (which may be a bit funky because UTC, I can help if you get stuck).

As an alternative, inspect the last polled sensor history to understand when updates occurred, and not the API used counter. 11:23 was me forcing an update earlier today.

<img width="588" alt="image" src="https://github.com/user-attachments/assets/ac49918a-4161-44b5-8b3a-53d6f17ed600" />


Implementing in the integration would require creating additional counters, config/options flow modification, translations, a schema bump for the usage cache, schema bump for entry options, documentation amendment including image updates, and scenario testing. The config/option change would need to add a "how many API calls are reserved for force updates" setting.

Not a bad idea, but a non-trivial one.

**Comment by BJReplay** [comment] 2024-12-18 07:46
> Guys I think you are missing the point.

Look, this might be an example of why oziee deleted his repo.

You are welcome to:
- fork the repo
- implement your own changes
- submit a PR for our consideration on inclusion here.

But we have already said, several times, that this is by design.

When you say we're missing the point, it really does sound like you are not considering that we might have discussed this (we have) and already reached a conclusion (we have) and, in this very issue, said "no, we've considered it, but won't be changing the way it operates".

Saying that we're missing the point is at best tone deaf, and at worst ungrateful, but, because it is difficult to read intent in the written word, I will assume that you missed the intent that we won't be changing this, and I will assume that you weren't intending to be rude.

But, unless you are willing and able to contribute a robust solution, rather than just asking for something that we have said several times that we are unwilling to provide, please don't keep asking with the opening statement that we're missing the point.

We're not.

**Comment by autoSteve** [comment] 2024-12-18 07:51
Automation to increment an input number helper:

```yaml
alias: Increment true Solcast API count
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.solcast_pv_forecast_api_last_polled
conditions: []
actions:
  - action: input_number.increment
    metadata: {}
    data: {}
    target:
      entity_id: input_number.true_solcast_api_count
mode: single
```

Add a Time & Date integration.

<img width="382" alt="image" src="https://github.com/user-attachments/assets/09e2caec-3a44-4c0f-92c5-91cb6b72273c" />

And an automation to reset:

```yaml
alias: Reset true Solcast API count
description: ""
triggers:
  - trigger: template
    value_template: "{{ states('sensor.time_utc')  == '00:00'}}"
conditions: []
actions:
  - action: input_number.set_value
    metadata: {}
    data:
      value: 0
mode: single
```

Sorted. But untested.

**Comment by autoSteve** [comment] 2024-12-18 08:13
After midnight reset automation edit (the entity_id was missing, oops), the input number increments as expected, and the UTC reset occurs.

<img width="562" alt="image" src="https://github.com/user-attachments/assets/a19051ff-908c-41ab-8444-00eff5f3cce1" />
