### ISSUE TITLE
I have problem integration HA

### ISSUE THREAD

**Issue by reprogerman** [BJReplay/ha-solcast-solar#9] opened 2024-06-04 09:06 UTC
### The problem

Thank you for taking over and creating this repository.  I have a problem.  I have removed all previous traces of hacs and HA.  The hacs integration works, it downloads and so far everything is fine, but in integrations to insert the apikey it tells me that it cannot be imported from the UI.  It doesn't appear in solcast searches.  What can be?

### What version of Solcast Integration has the issue?

Las version

### Logs debug/info/error output

```txt
I dont have logs
```

**Comment by cromefire** [comment] 2024-06-05 21:34
If you used the my home assistant button, it's probably a duplicate of #8 and you just need to remove the integration and custom repo and just follow the manual instructions or the updated link.

**Comment by reprogerman** [comment] 2024-06-05 21:40
Muchas gracias. Ya funciona

**Comment by BJReplay** [comment] 2024-06-05 23:38
Closed in https://github.com/BJReplay/ha-solcast-solar/pull/11

**Closed by BJReplay** 2024-06-05 23:38 UTC
