### ISSUE TITLE
TypeError on Brand New Install - HA Dev Containers (vscode ➜ /workspaces/core/config (dev))

### ISSUE THREAD

**Issue by BJReplay** [BJReplay/ha-solcast-solar#214] opened 2024-11-06 12:08 UTC
**Describe the bug**
`TypeError: '<' not supported between instances of 'str' and 'datetime.datetime'` thrown on initial set up of Solcast integration. 

**To Reproduce**
1. Install Home Assistant in Visual Studio Dev Containers as per https://developers.home-assistant.io/docs/development_environment/#developing-with-visual-studio-code--devcontainer
2. Install HACS into this environment and restart as required.
3. Add the Solcast (v4.2.5 at the time of this issue) integration to HACS as a custom repository and restart as required
4. Add the Solcast Integration and configure.
5. See error

Error is on check to see if auto-update is stale near the bottom of the logs:

```
2024-11-06 11:46:08.058 DEBUG (MainThread) [custom_components.solcast_solar] UTC times are converted to Australia/Sydney
2024-11-06 11:46:08.058 DEBUG (MainThread) [custom_components.solcast_solar] Checking whether auto update forecast is stale
```

It looks like this bomb goes off if there's never been an update - i.e. for a brand new install.

The assumption - incorrect - is that `solcast.get_data()['last_attempt']` always returns a date.

As it is getting late, and my eyes are getting sore, I haven't set break points on all accesses of last_attempt - but that's something that I now know **how to do** so I am co-assigning this to me and you, though I'll probably defer the fix your superior coding skilz.

I've finally got myself up and running able to debug and set breakpoints and all that - it's been a steep learning curve and a well needed distraction.

Very pleasing to see the logging on the the first run set up of all the sensors and statistics.

**Expected behavior**
Integration is configured.

**Screenshots**
![image](https://github.com/user-attachments/assets/51cabd74-31af-4f9c-906f-7920724519a1)

**Logs**

I confirm:
- [X] I have attached **debug** logs 
- [ ] I have embedded **debug** logs in the issue description (enclosed in tick marks ``` for proper formatting)
- [ ] Confirmed **debug** logs are not required for this issue

**Solcast Integration Version**
 - v4.2.5

**Desktop (please complete the following information):**
 - OS: Windows
 - Edge Dev 

**Additional context**

Logs below.

```
2024-11-06 11:45:24.442 INFO (MainThread) [homeassistant.setup] Setting up select
2024-11-06 11:45:24.509 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of aiofiles>=23.2.0
2024-11-06 11:45:26.759 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of datetime>=4.3
2024-11-06 11:45:29.063 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of isodate>=0.6.1
2024-11-06 11:46:06.111 INFO (MainThread) [homeassistant.setup] Setting up solcast_solar
2024-11-06 11:46:06.118 DEBUG (MainThread) [custom_components.solcast_solar] Auto-update options: {'auto_update': 2}
2024-11-06 11:46:06.118 DEBUG (MainThread) [custom_components.solcast_solar] Estimate to use options: {'key_estimate': 'estimate'}
2024-11-06 11:46:06.119 DEBUG (MainThread) [custom_components.solcast_solar] Attribute options: {'attr_brk_estimate': True, 'attr_brk_estimate10': True, 'attr_brk_estimate90': True, 'attr_brk_site': True, 'attr_brk_halfhourly': True, 'attr_brk_hourly': True, 'attr_brk_detailed': False}
2024-11-06 11:46:06.119 DEBUG (MainThread) [custom_components.solcast_solar] Custom sensor options: {'customhoursensor': 1}
2024-11-06 11:46:06.119 DEBUG (MainThread) [custom_components.solcast_solar] Hard limit: {'hard_limit_api': '100.0'}
2024-11-06 11:46:06.119 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Configuration directory is /workspaces/core/config
2024-11-06 11:46:06.119 DEBUG (MainThread) [custom_components.solcast_solar] Session headers: {'Accept': 'application/json', 'User-Agent': 'ha-solcast-solar-integration/4.2'}
2024-11-06 11:46:06.131 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Sites cache does not yet exist
2024-11-06 11:46:06.131 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Connecting to https://api.solcast.com.au/rooftop_sites?format=json&api_key=******bvvHxW
2024-11-06 11:46:06.298 INFO (MainThread) [custom_components.solcast_solar.solcastapi] HTTP session returned status 200/Success in __sites_data()
2024-11-06 11:46:06.303 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Writing sites cache
2024-11-06 11:46:06.312 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Sites data: {'sites': [{'name': 'BLAH', 'resource_id': 'a546-98c5-53c5-d101', 'capacity': 5, 'capacity_dc': 4.85, 'longitude': **.******, 'latitude': **.******, 'azimuth': -123, 'tilt': 5, 'install_date': '2012-04-18T14:00:00.0000000Z', 'loss_factor': 0.8, 'tags': ['Home', 'St Kilda West', 'Flat Roof', 'Home Assistant'], 'location': 'St Kilda West, VIC Australia', 'api_key': '******bvvHxW'}], 'page_count': 1, 'current_page': 1, 'total_records': 1}
2024-11-06 11:46:06.312 INFO (MainThread) [custom_components.solcast_solar.solcastapi] Sites loaded
2024-11-06 11:46:06.314 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Usage cache does not yet exist for ******bvvHxW
2024-11-06 11:46:06.314 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] Creating usage cache for ******bvvHxW, assuming zero API used
2024-11-06 11:46:06.314 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Writing API usage cache file: /workspaces/core/config/solcast-usage.json
2024-11-06 11:46:06.325 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] API counter for ******bvvHxW is 0/5
2024-11-06 11:46:06.325 DEBUG (MainThread) [custom_components.solcast_solar] Successful init
2024-11-06 11:46:06.325 INFO (MainThread) [custom_components.solcast_solar] 
-------------------------------------------------------------------
Solcast integration version: v4.2.5

This is a custom integration. When troubleshooting a problem, after
reviewing open and closed issues, and the discussions, check any
automation is functioning correctly (unless auto-update is
enabled). Troubleshooting tips available at:
https://github.com/BJReplay/ha-solcast-solar/discussions/38

Beta versions may also have addressed issues so look at those.

If all else fails, then open an issue and our community will try to
help: https://github.com/BJReplay/ha-solcast-solar/issues
-------------------------------------------------------------------
2024-11-06 11:46:06.328 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] There is no solcast.json to load, so fetching solar forecast, including past forecasts
2024-11-06 11:46:06.329 INFO (MainThread) [custom_components.solcast_solar.solcastapi] Getting forecast update for site a546-98c5-53c5-d101
2024-11-06 11:46:06.329 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Polling API for site a546-98c5-53c5-d101 lastday 2024-11-13 numhours 170
2024-11-06 11:46:06.332 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Fetch data url: https://api.solcast.com.au/rooftop_sites/a546-98c5-53c5-d101/estimated_actuals
2024-11-06 11:46:06.332 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Fetching forecast
2024-11-06 11:46:06.754 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Fetch successful
2024-11-06 11:46:06.755 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] API returned data, API counter incremented from 0 to 1
2024-11-06 11:46:06.755 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Writing API usage cache file: /workspaces/core/config/solcast-usage.json
2024-11-06 11:46:06.779 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] HTTP session returned data type <class 'dict'>
2024-11-06 11:46:06.780 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] HTTP session status 200/Success
2024-11-06 11:46:06.861 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Fetch data url: https://api.solcast.com.au/rooftop_sites/a546-98c5-53c5-d101/forecasts
2024-11-06 11:46:06.861 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Fetching forecast
2024-11-06 11:46:07.374 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Fetch successful
2024-11-06 11:46:07.375 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] API returned data, API counter incremented from 1 to 2
2024-11-06 11:46:07.375 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Writing API usage cache file: /workspaces/core/config/solcast-usage.json
2024-11-06 11:46:07.404 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] HTTP session returned data type <class 'dict'>
2024-11-06 11:46:07.405 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] HTTP session status 200/Success
2024-11-06 11:46:07.410 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] 341 records returned
2024-11-06 11:46:07.515 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Forecasts dictionary length 671
2024-11-06 11:46:07.515 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Undampened forecasts dictionary length 671
2024-11-06 11:46:07.515 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] HTTP data call processing took 0.094 seconds
2024-11-06 11:46:07.522 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Build per-site and total processing took 0.007 seconds for dampened
2024-11-06 11:46:07.533 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Build per-site and total processing took 0.007 seconds for un-dampened
2024-11-06 11:46:07.541 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Forecast data from 2024-11-06 to 2024-11-13 contains all intervals
2024-11-06 11:46:07.541 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Calculating splines
2024-11-06 11:46:07.596 WARNING (MainThread) [asyncio] Executing <Task pending name='config entry setup Solcast Solar solcast_solar 01JC0MQM4W690S7H8SJDTMG8EW' coro=<ConfigEntry.async_setup_locked() running at /workspaces/core/homeassistant/config_entries.py:783> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:391, Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:449> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.12/asyncio/tasks.py:767] created at /workspaces/core/homeassistant/util/async_.py:45> took 0.187 seconds
2024-11-06 11:46:07.602 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Saved dampened forecast cache
2024-11-06 11:46:07.613 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Saved undampened forecast cache
2024-11-06 11:46:07.613 INFO (MainThread) [custom_components.solcast_solar.solcastapi] Forecast update completed successfully
2024-11-06 11:46:07.614 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Previous auto update was at: 2024-11-06 19:12:00 (if auto-update was enabled at the time)
2024-11-06 11:46:07.614 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Auto update total seconds: 86400, divisions: 5, interval: 17280 seconds
2024-11-06 11:46:07.614 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Auto update will update forecasts 5 times over 24 hours
2024-11-06 11:46:07.614 INFO (MainThread) [custom_components.solcast_solar.coordinator] Auto update: Forecast updates for tomorrow at 00:00:00, 04:48:00, 09:36:00, 14:24:00, 19:12:00
2024-11-06 11:46:07.616 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Started task listeners
2024-11-06 11:46:07.616 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Started task check_fetch
2024-11-06 11:46:07.616 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Started task midnight_update
2024-11-06 11:46:07.616 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Finished fetching solcast_solar data in 0.000 seconds (success: True)
2024-11-06 11:46:07.640 INFO (MainThread) [homeassistant.components.sensor] Setting up solcast_solar.sensor
2024-11-06 11:46:07.651 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_forecast_today
2024-11-06 11:46:07.673 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_peak_forecast_today
2024-11-06 11:46:07.690 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_peak_time_today
2024-11-06 11:46:07.705 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_forecast_this_hour
2024-11-06 11:46:07.721 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_forecast_remaining_today
2024-11-06 11:46:07.739 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_forecast_next_hour
2024-11-06 11:46:07.755 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_forecast_next_x_hours
2024-11-06 11:46:07.771 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_forecast_tomorrow
2024-11-06 11:46:07.794 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_peak_forecast_tomorrow
2024-11-06 11:46:07.812 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_peak_time_tomorrow
2024-11-06 11:46:07.826 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_api_used
2024-11-06 11:46:07.833 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_api_limit
2024-11-06 11:46:07.843 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_api_last_polled
2024-11-06 11:46:07.851 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_forecast_day_3
2024-11-06 11:46:07.872 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_forecast_day_4
2024-11-06 11:46:07.894 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_forecast_day_5
2024-11-06 11:46:07.922 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_forecast_day_6
2024-11-06 11:46:07.953 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_forecast_day_7
2024-11-06 11:46:07.987 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_power_now
2024-11-06 11:46:07.993 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_power_in_30_minutes
2024-11-06 11:46:08.004 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_power_in_1_hour
2024-11-06 11:46:08.016 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.solcast_pv_forecast_hard_limit_set
2024-11-06 11:46:08.026 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.solcast_solar entity: sensor.blah
2024-11-06 11:46:08.046 INFO (MainThread) [homeassistant.components.select] Setting up solcast_solar.select
2024-11-06 11:46:08.049 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new select.solcast_solar entity: select.solcast_pv_forecast_use_forecast_field
2024-11-06 11:46:08.058 DEBUG (MainThread) [custom_components.solcast_solar] UTC times are converted to Australia/Sydney
2024-11-06 11:46:08.058 DEBUG (MainThread) [custom_components.solcast_solar] Checking whether auto update forecast is stale
2024-11-06 11:46:08.058 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Solcast Solar for solcast_solar
Traceback (most recent call last):
  File "/workspaces/core/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/config/custom_components/solcast_solar/__init__.py", line 259, in async_setup_entry
    if coordinator.interval_just_passed is not None and solcast.get_data()['last_attempt'] < coordinator.interval_just_passed - timedelta(minutes=1):
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'datetime.datetime'
2024-11-06 11:46:08.062 WARNING (MainThread) [asyncio] Executing <Task finished name='config entry setup Solcast Solar solcast_solar 01JC0MQM4W690S7H8SJDTMG8EW' coro=<ConfigEntry.async_setup_locked() done, defined at /workspaces/core/homeassistant/config_entries.py:767> result=None created at /workspaces/core/homeassistant/util/async_.py:45> took 0.423 seconds
2024-11-06 11:50:10.243 INFO (Recorder) [homeassistant.components.sensor.recorder] Compiling initial sum statistics for sensor.solcast_pv_forecast_forecast_today, zero point set to 18.352
2024-11-06 11:50:10.243 INFO (Recorder) [homeassistant.components.sensor.recorder] Compiling initial sum statistics for sensor.solcast_pv_forecast_forecast_tomorrow, zero point set to 22.944
2024-11-06 11:50:10.244 INFO (Recorder) [homeassistant.components.sensor.recorder] Compiling initial sum statistics for sensor.solcast_pv_forecast_forecast_day_3, zero point set to 23.8071
2024-11-06 11:50:10.244 INFO (Recorder) [homeassistant.components.sensor.recorder] Compiling initial sum statistics for sensor.solcast_pv_forecast_forecast_day_4, zero point set to 25.6473
2024-11-06 11:50:10.244 INFO (Recorder) [homeassistant.components.sensor.recorder] Compiling initial sum statistics for sensor.solcast_pv_forecast_forecast_day_5, zero point set to 24.2209
2024-11-06 11:50:10.244 INFO (Recorder) [homeassistant.components.sensor.recorder] Compiling initial sum statistics for sensor.solcast_pv_forecast_forecast_day_6, zero point set to 29.3056
2024-11-06 11:50:10.244 INFO (Recorder) [homeassistant.components.sensor.recorder] Compiling initial sum statistics for sensor.solcast_pv_forecast_forecast_day_7, zero point set to 22.4381
```

**Comment by autoSteve** [comment] 2024-11-06 20:38
This is a brilliant test. And a fascinating result, @BJReplay.

`last_attempt` needs to be set to UTC now() when the `solcast.json` is created should it not exist, but only when auto-update is enabled. I need to check when `last_attempt` gets set, and to what. 

On a quick look, the root of this is that `last_attempt` seems to be a string, and not a datetime, so it is getting set weirdly somewhere.

It needs a much deeper look when not doing bank business to work out why this happens.

Good on you getting that lot set up.

**Comment by BJReplay** [comment] 2024-11-06 22:09
I had a step through - it does seem to be set to Unix epoch date, then updated, but the failure is in the logged line: the retrieval in get_data() returns a string from the weakly typed dict.

Beyond my skilz to solve other than to suggest that on reading a typedict might be the solution?

**Comment by BJReplay** [comment] 2024-11-07 03:07
> Beyond my skilz to solve other than to suggest that on reading a typeddict might be the solution?

And I tried `@dataclass` and TypedDict but ran into a skilz barrier pretty quickly where I thought that strongly typing might be the **neat** solution where accepting that it's going to be returned as string and converting back to a date time is probably the **necessary** solution.

But I can confirm that in quite a few attempts, on every repro, that `last_attempt` was always initialised and always stored a datetime, but it was the retrieval that folded it back to a string.

**Comment by autoSteve** [comment] 2024-11-07 04:42
I looked. The only place this could be creeping in that I have spotted is in `JSONDecoder()`.

That function is responsible for converting ISO format date/times to `datetime.datetime` types, and it uses a regular expression to determine whether it should. The regex is simple, and ISO format date/times do not magically change format, so it's a head scratcher for now.

To work around this until the root cause of the issue can be found I have committed a try/except block, and on a wild hunch have set the `last_attempt` to UTC `now()` for a fresh install that fetches forecast when new sites are detected.

Examining the contents of `last_attempt` when the comparison happens would be useful. Is it an ISO format date/time?

**Comment by autoSteve** [comment] 2024-11-07 05:27
> I looked. The only place this could be creeping in that I have spotted is in `JSONDecoder()`.

Actually not. So it gets weirder.

For a fresh install `solcast.json` does not exist, so it is obviously not loaded, hence `JSONDecoder()` is not implicated.

For fresh, each site forecast is read from Solcast using `__http_data_call(do_past=True)` in `load_saved_data()`, with `_loaded_data` set to True. For this curcumstance `last_attempt` would be default in v4.2.5. In the earlier commit I have corrected this, with it now set to UTC `now()`.

It'll be interesting if you can replicate it given these changes. If you can replicate it then `Auto update freshness could not be determined` will be warned. If not, then `Auto update forecast is fresh` debug.

**Comment by BJReplay** [comment] 2024-11-07 08:10
I will see if I can grab those changes and test.

That's probably gonna be copy-pasta over the top, but should work. 

In answer to your questions as I recall as I type on my phone - the json element is always a date when inspected in the VS Studio Watch window. Probably ISO format, but in any case, a date.

My gut feeling is that get_data() turns it into a string.

Will test later tonight.

**Comment by autoSteve** [comment] 2024-11-07 08:30
Interesting.

I tested a fresh-out-of-box install with the opera house key.

String, clearly.

```
WARNING (MainThread) [custom_components.solcast_solar] Auto update freshness could not be determined
```

**Comment by autoSteve** [comment] 2024-11-07 08:39
I found it. In `get_forecast_update()`.

Yeah, nah... This returns a string.

```
            last_attempt = dt.now(timezone.utc).isoformat()
```

Yeah, this is a `datetime`...

```
            last_attempt = dt.now(timezone.utc)
```

**Comment by BJReplay** [comment] 2024-11-07 08:48
> Yeah, nah... This returns a string.

With the benefit of hindsight, of course ISO format is a string!

**Comment by autoSteve** [comment] 2024-11-07 08:49
I know, right? What the hell was I thinking? (Re-examines life...)

**Closed** 2024-11-22 09:07 UTC
Labels: bug
