### ISSUE TITLE
Solcast update-new uses an unknown action

### ISSUE THREAD

**Issue by kams19** [BJReplay/ha-solcast-solar#217] opened 2024-11-11 12:52 UTC
### The problem

I am getting this error- 
"Solcast update-new uses an unknown action
Error ⸱ Reported by Automation
The automation "Solcast update-new" (automation.solcast_update_new) has an unknown action: solcast_solar.update_forecasts.

This error prevents the automation from running correctly. Maybe this action is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](http://192.168.1.5:8123/config/automation/edit/1725985653577) and remove this action.

Select Submit below to confirm you have fixed this automation."

I can see the solcast_solar.update_forecasts is still available so not sure why I am seeing this error.

### What version of Solcast Integration has the issue?

v4.2.5

### What version of Home Assistant are you using?

2024.11.1

### Diagnostics information

I am getting this error- 
"Solcast update-new uses an unknown action
Error ⸱ Reported by Automation
The automation "Solcast update-new" (automation.solcast_update_new) has an unknown action: solcast_solar.update_forecasts.

This error prevents the automation from running correctly. Maybe this action is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](http://192.168.1.5:8123/config/automation/edit/1725985653577) and remove this action.

Select Submit below to confirm you have fixed this automation."

I can see the 

### Logs debug/info/error output

```txt
I am getting this error- 
"Solcast update-new uses an unknown action
Error ⸱ Reported by Automation
The automation "Solcast update-new" (automation.solcast_update_new) has an unknown action: solcast_solar.update_forecasts.

This error prevents the automation from running correctly. Maybe this action is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](http://192.168.1.5:8123/config/automation/edit/1725985653577) and remove this action.

Select Submit below to confirm you have fixed this automation."
```

**Comment by kams19** [comment] 2024-11-11 12:53
Automation script:
alias: Solcast update-new
description: ""
mode: single
triggers:
  - value_template: >-
      {% set nr = as_datetime(state_attr('sun.sun','next_rising')) | as_local %}
      {% set ns = as_datetime(state_attr('sun.sun','next_setting')) | as_local
      %} {% set api_request_limit = 10 %} {% if nr > ns %}
        {% set nr = nr - timedelta(hours = 24) %} 
      {% endif %} {% set hours_difference = (ns - nr) %} {% set interval_hours =
      hours_difference / api_request_limit %} {% set ns = namespace(match =
      false) %} {% for i in range(api_request_limit) %}
        {% set start_time = nr + (i * interval_hours) %}
        {% if ((start_time - timedelta(seconds=30)) <= now()) and (now() <= (start_time + timedelta(seconds=30))) %}
          {% set ns.match = true %}
        {% endif %}
      {% endfor %} {{ ns.match }}
    trigger: template
conditions:
  - condition: sun
    before: sunset
    after: sunrise
actions:
  - delay:
      seconds: "{{ range(30, 360)|random|int }}"
  - data: {}
    action: solcast_solar.update_forecasts

**Comment by autoSteve** [comment] 2024-11-11 21:00
Additional information and context required. (My crystal ball broke last issue reported.)

Did this spontaneously break? Is it a new install or existing? Is the integration running? If the integration is not loaded then the action will not exist.

Status shown here... Devices & Services | Integrations | Solcast Solar.

<img width="993" alt="image" src="https://github.com/user-attachments/assets/cc8d4f7b-92f1-469f-8d8b-4a61222a05d2">

**Comment by autoSteve** [comment] 2024-11-11 21:47
If this is an existing install that has been upgraded to v4.2.5 then a potential change in your configuration could be to disable that automation, and enable auto-update from sunrise to sunset in the integration configuration. That will accomplish the same update frequency.

This may expose the root cause, too.

> I can see the solcast_solar.update_forecasts is still available so not sure why I am seeing this error.

I assume that you are seeing this in the developer tools actions? If so then that would imply that the integration is loaded.

A brief history might help. e.g. "I was running happily on v4.2.4, upgraded to v4.2.5 and it ran for a few days then my automation spontaneously broke"... or whatever happened. The action being AWOL is likely a symptom of the true root cause, so debug-level logs may uncover what is going on.

**Comment by BJReplay** [comment] 2024-11-12 00:09
If I take the script you added in the [comment above](https://github.com/BJReplay/ha-solcast-solar/issues/217#issuecomment-2468112360) and paste it into a new automation and run it, I don't get that error.

That confirms that the automation script is valid, and that the action exists in a normal installation.

You will need to provide more information or provide debug as described in #38 logs or both.

**Comment by autoSteve** [comment] 2024-11-12 10:28
The Problem: Error message about an action missing despite 4,673 folks running v4.2.5 without a peep.

The diagnostics information: Nothing except the same error message.

Context: We got nothin' except the HA and integration version.

I tried to look for hidden clues. Found this.

> I can see the [trails off...]

...red door and I want it painted black? (Soz, just watched Full Metal Jacket again.)

Initial triage: Your automation's good, but we got error message. @autoSteve's crystal ball is broken, so not helping.

🤣🤣🤣 Forgive the jibes, but again, I'm in a Full Metal Jacket mood.

We do honestly love to help. But we do honestly cry out for a little more than, "It's busted."

**Comment by kams19** [comment] 2024-11-12 11:16
Thanks for your response. 
There was no error until 16Oct, something changed after that and it .

I have enabled debug logging on the addon settings and here is what I have got after that:
**2024-11-11 11:47:41.269 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] Forecast update for site 7086-fc55-e9ed-92b4 failed so not getting remaining sites
2024-11-11 11:47:41.270 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] At least one site forecast failed to fetch, so forecast has not been built
2024-11-11 12:42:54.268 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] API polling limit exhausted, not getting forecast for site 7086-fc55-e9ed-92b4, API used is 5/5
2024-11-11 12:42:54.273 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] Forecast update for site 7086-fc55-e9ed-92b4 failed so not getting remaining sites
2024-11-11 12:42:54.274 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] At least one site forecast failed to fetch, so forecast has not been built
2024-11-11 12:51:45.684 ERROR (MainThread) [custom_components.hacs] <Integration oziee/ha-solcast-solar> GitHub returned 404 for https://api.github.com/repos/oziee/ha-solcast-solar
2024-11-11 12:51:45.820 ERROR (MainThread) [custom_components.hacs] <Integration oziee/ha-solcast-solar> No manifest.json file found 'custom_components/None/manifest.json'
2024-11-11 12:52:01.307 ERROR (MainThread) [custom_components.hacs] <Integration oziee/ha-solcast-solar> GitHub returned 404 for https://api.github.com/repos/oziee/ha-solcast-solar
2024-11-11 12:52:01.430 ERROR (MainThread) [custom_components.hacs] <Integration oziee/ha-solcast-solar> No manifest.json file found 'custom_components/None/manifest.json'
2024-11-11 13:35:17.265 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] API polling limit exhausted, not getting forecast for site 7086-fc55-e9ed-92b4, API used is 5/5
2024-11-11 13:35:17.267 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] Forecast update for site 7086-fc55-e9ed-92b4 failed so not getting remaining sites
2024-11-11 13:35:17.268 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] At least one site forecast failed to fetch, so forecast has not been built
2024-11-11 14:29:12.266 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] API polling limit exhausted, not getting forecast for site 7086-fc55-e9ed-92b4, API used is 5/5
2024-11-11 14:29:12.267 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] Forecast update for site 7086-fc55-e9ed-92b4 failed so not getting remaining sites
2024-11-11 14:29:12.268 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] At least one site forecast failed to fetch, so forecast has not been built
2024-11-11 15:26:05.264 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] API polling limit exhausted, not getting forecast for site 7086-fc55-e9ed-92b4, API used is 5/5
2024-11-11 15:26:05.267 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] Forecast update for site 7086-fc55-e9ed-92b4 failed so not getting remaining sites
2024-11-11 15:26:05.268 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] At least one site forecast failed to fetch, so forecast has not been built
2024-11-12 09:02:16.255 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] API polling limit exhausted, not getting forecast for site 0a4f-9e47-65ce-2782, API used is 5/5
2024-11-12 09:02:16.256 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] Forecast update for the last site queued failed (0a4f-9e47-65ce-2782) - API use count may be odd
2024-11-12 09:02:16.256 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] At least one site forecast failed to fetch, so forecast has not been built
2024-11-12 09:59:42.264 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] API polling limit exhausted, not getting forecast for site 7086-fc55-e9ed-92b4, API used is 5/5
2024-11-12 09:59:42.267 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] Forecast update for site 7086-fc55-e9ed-92b4 failed so not getting remaining sites
2024-11-12 09:59:42.268 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] At least one site forecast failed to fetch, so forecast has not been built
2024-11-12 10:24:16.345 DEBUG (MainThread) [custom_components.solcast_solar] Auto-update options: {'auto_update': 0}
2024-11-12 10:24:16.345 DEBUG (MainThread) [custom_components.solcast_solar] Estimate to use options: {'key_estimate': 'estimate'}
2024-11-12 10:24:16.345 DEBUG (MainThread) [custom_components.solcast_solar] Attribute options: {'attr_brk_detailed': False, 'attr_brk_estimate': True, 'attr_brk_estimate10': True, 'attr_brk_estimate90': True, 'attr_brk_halfhourly': True, 'attr_brk_hourly': True, 'attr_brk_site': True}
2024-11-12 10:24:16.345 DEBUG (MainThread) [custom_components.solcast_solar] Custom sensor options: {'customhoursensor': 1}
2024-11-12 10:24:16.345 DEBUG (MainThread) [custom_components.solcast_solar] Hard limit: {'hard_limit_api': '100.0'}
2024-11-12 10:24:16.345 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Configuration directory is /config
2024-11-12 10:24:16.345 DEBUG (MainThread) [custom_components.solcast_solar] Session headers: {'Accept': 'application/json', 'User-Agent': 'ha-solcast-solar-integration/4.2'}
2024-11-12 10:24:16.354 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Sites cache exists
2024-11-12 10:24:16.354 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Connecting to https://api.solcast.com.au/rooftop_sites?format=json&api_key=******qWLbMU
2024-11-12 10:24:16.707 INFO (MainThread) [custom_components.solcast_solar.solcastapi] HTTP session returned status 200/Success in __sites_data()
2024-11-12 10:24:16.709 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Writing sites cache
2024-11-12 10:24:16.711 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Sites data: {'sites': [{'name': 'East Facing Array', 'resource_id': '7086-fc55-e9ed-92b4', 'capacity': 6, 'capacity_dc': 3.36, 'longitude': **.******, 'latitude': **.******, 'azimuth': -91, 'tilt': 41, 'install_date': '2024-04-16T23:00:00.0000000Z', 'loss_factor': 0.99, 'tags': ['Home-East'], 'api_key': '******qWLbMU'}, {'name': 'West Facing Arrray', 'resource_id': '0a4f-9e47-65ce-2782', 'capacity': 6, 'capacity_dc': 3.36, 'longitude': **.******, 'latitude': **.******, 'azimuth': 90, 'tilt': 41, 'install_date': '2024-04-16T23:00:00.0000000Z', 'loss_factor': 0.99, 'tags': ['Home West'], 'api_key': '******qWLbMU'}], 'page_count': 1, 'current_page': 1, 'total_records': 2}
2024-11-12 10:24:16.711 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Usage cache exists for ******qWLbMU
2024-11-12 10:24:16.713 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Usage cache for ******qWLbMU last reset 2024-11-12 00:00:00
2024-11-12 10:24:16.713 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] API counter for ******qWLbMU is 5/5
2024-11-12 10:24:16.713 DEBUG (MainThread) [custom_components.solcast_solar] Successful init
2024-11-12 10:24:16.713 INFO (MainThread) [custom_components.solcast_solar] Solcast integration version: v4.2.5
2024-11-12 10:24:16.871 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Data cache /config/solcast.json exists, file type is <class 'dict'>
2024-11-12 10:24:16.887 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Data cache /config/solcast-undampened.json exists, file type is <class 'dict'>
2024-11-12 10:24:17.006 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Build per-site and total processing took 0.118 seconds for dampened
2024-11-12 10:24:17.052 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Build per-site and total processing took 0.010 seconds for un-dampened
2024-11-12 10:24:17.055 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Forecast data from 2024-11-12 to 2024-11-19 contains all intervals
2024-11-12 10:24:17.055 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Calculating splines
2024-11-12 10:24:17.083 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Started task listeners
2024-11-12 10:24:17.083 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Started task check_fetch
2024-11-12 10:24:17.083 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Started task midnight_update
2024-11-12 10:24:17.083 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Finished fetching solcast_solar data in 0.000 seconds (success: True)
2024-11-12 10:24:17.134 DEBUG (MainThread) [custom_components.solcast_solar] UTC times are converted to Europe/London
2024-11-12 10:52:22.268 INFO (MainThread) [custom_components.solcast_solar] Action: Fetching forecast
2024-11-12 10:52:22.269 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Checking for stale usage cache
2024-11-12 10:52:22.269 INFO (MainThread) [custom_components.solcast_solar.solcastapi] Getting forecast update for site 7086-fc55-e9ed-92b4
2024-11-12 10:52:22.269 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Polling API for site 7086-fc55-e9ed-92b4 lastday 2024-11-20 numhours 182
2024-11-12 10:52:22.271 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] API polling limit exhausted, not getting forecast for site 7086-fc55-e9ed-92b4, API used is 5/5
2024-11-12 10:52:22.272 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] Forecast update for site 7086-fc55-e9ed-92b4 failed so not getting remaining sites
2024-11-12 10:52:22.273 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] At least one site forecast failed to fetch, so forecast has not been built
**

**Comment by autoSteve** [comment] 2024-11-12 11:31
Now we are talking. #debug!

You likely still have Oziee's repo enabled in HACS. Kill it. It is dead to you, and to the world. @BJReplay for the win.

```
2024-11-11 12:51:45.684 ERROR (MainThread) [custom_components.hacs] <Integration oziee/ha-solcast-solar> GitHub returned 404 for https://api.github.com/repos/oziee/ha-solcast-solar
2024-11-11 12:51:45.820 ERROR (MainThread) [custom_components.hacs] <Integration oziee/ha-solcast-solar> No manifest.json file found 'custom_components/None/manifest.json'
2024-11-11 12:52:01.307 ERROR (MainThread) [custom_components.hacs] <Integration oziee/ha-solcast-solar> GitHub returned 404 for https://api.github.com/repos/oziee/ha-solcast-solar
2024-11-11 12:52:01.430 ERROR (MainThread) [custom_components.hacs] <Integration oziee/ha-solcast-solar> No manifest.json file found 'custom_components/None/manifest.json'
```

The API count is seemingly pegged at 5/5. We're a while away from UTC midnight reset, so that will come.

Some questions: Why is 5 set as the limit? You have two Solcast sites. You have ten API calls as a hobbyist, so why not use them all? The integration works this stuff out, because two sites.

Solcast dropped an API call that gave us the current state of play re. API usage on a plate. We now have to 'guess', which is why the integration now has a config option for the limit. If you have two sites, set to ten. Each update will use two, because two sites and the integration will keep track of this.

> something changed after that and it . [trails off...]

saw a red door, and wanted it painted black? 🤣

**Comment by BJReplay** [comment] 2024-11-12 11:39
@autoSteve this is wild speculation, but when oziee first nuked his github repo from orbit, my HA host simultaneously (within experimental observability) suffered a significant failure, and once I got it back up and running, HA wouldn't come up, because HACS / HA couldn't reach the oziee github repo. 

I had to a) kill the custom_components folder b) edit the config files, and c) perform other major surgery to get HA up and running.  That's why I cloned the most up to date clone that I could find, and why we find ourselves here.

It seems that some people are only now just swapping from the oziee integration, but for whatever reason, HACS / HA is hanging on pretty tight to it.

THis repo should be installed in the same folder, so it's just config that is pointing to oziee, and it's just config and automation, that is calling (presumably) our code (unless the oziee repo was somehow installed in a different folder).

Very strange that we've got two of these in a couple of weeks where remants of oziee config and automations survive (and eat API calls).

**Comment by autoSteve** [comment] 2024-11-12 11:50
Well, that Oziee committed GitHub suicide is what it is.

I did not have to commit any major jiggery to kill his off. Then again, I am HAOS in a VM on Proxmox.

We should be byte-for-byte compatible with his short-comings, including install folder and data files (which get an upgrade schema on v4.2.5). Our short-comings are somewhat shorter, however... Hopefully zilch compared to his.

Yep. If his repo was installed in a different folder then this would likely explode things.

This looks like a vanilla HAOS install though (unspecified) using HACS custom repo. of Oziee originally. We _should_ just slide on over the top and expunge it.

There be Oziee demons out there. Mark my words...

So @kams19, what happened on October 16th? What did you do?

**Comment by BJReplay** [comment] 2024-11-12 12:00
I've still got my config backups from May 31 when this all went pear shaped.

**Comment by autoSteve** [comment] 2024-11-12 12:04
> whether we can look for and clean up oziee config on install?

This we could actually do.

But what we could not do is to cause a Home Asisstant restart to make it stick/work seamlessly. The best we could do would be to error to the moon and back about it, and possibly refuse to even load with a, "YO! RESTART HA NOW!!!" on-load status, or something a little less shouty.

The user initiates HA restarts. An automation can not from all I know, (which is a good thing) and that would be required to re-load all Python and expunge other folders.

But what are the permutations? I hear you ask. Pfft...

This (and the defunct Oziee) integration could be installed in any folder name. I can cope with that. Read the manifest file for each and every folder in custom-components, and kill any competitors not matching the current release...

**Comment by autoSteve** [comment] 2024-11-12 12:06
But I digress... This does not explain the lack of a `solcast_solar.update_forecasts` action in the HA service calls.

Where does it go? Is it still missing now, @kams19?

**Comment by BJReplay** [comment] 2024-11-12 12:07
> But what we could not do is to cause a Home Assistant restart to make it stick/work seamlessly.

No, but we can do what HACS does, and that is do the "Restart Required" notification thing that HACS does - which is actually a standard HA call, if I recall what I spotted running in debug mode the other day.  Let me find it and get back to you (tomorrow).

**Comment by BJReplay** [comment] 2024-11-12 12:10
`action: homeassistant.restart`

**Comment by autoSteve** [comment] 2024-11-12 12:12
> `action: homeassistant.restart`

A warm body or an automation can call that. An integration cannot without an authorised API key via the REST API.

**Comment by autoSteve** [comment] 2024-11-12 13:26
I'm on the verge of closing this one as `read the readme`, wthout some serious additional input.

This curcumstance is fascinating to me, so I'm leaving this open for now, and I would dearly love some further context, @kams19. Especially on the transition from Oziee to @BJReplay, if that's what you did.

The debug log looks clean, apart from having ripped through all API call quota for now, possibly setting five and not ten in config as the max in error, and aside from having Oziee's repo still hangin' round... No mention of a missing action.

**Comment by BJReplay** [comment] 2024-11-12 20:46
> An integration cannot without an authorised API key via the REST API.

I suspect that this is what HACS does (one way or another) is queue a restart required notification that sets up a repair (that sets up an automation?). 

Will investigate further and report back.

**Comment by autoSteve** [comment] 2024-11-12 21:46
> was under the impression that I need to half the total number

I can't wait for Solcast to bring back a REST call to get limit and usage, @BJReplay. I can see how this could be confusing, as it is not directly addressed in the readme.

> I have now deleted the addon for the previous Oziee solcast install.

I'm curious as to the steps involved here that led to this. There might well be a gap in the readme for transitioning from Oziee, or an FAQ might want writing. Maybe a step was missed in the readme. In any event, there are things that happened here that I just can't explain.

Welcome to this integration, @kams19! The current version is very much more robust than the ancient code you were running. Now that you have it up and running, as your logs show, enjoy! (And thanks for sharing that log.)

**Comment by autoSteve** [comment] 2024-11-20 19:46
I guess we'll never get more information to understand the underlying issue that occurred here.

**Comment by BJReplay** [comment] 2024-11-20 21:13
Someone mentioned on the community forum that they ended up with both oziee and bjreplay installed, and asked for assistance a couple of days ago. 

I did ask for logs, screenshots, and an issue to be raised.

Nothing since.

**Comment by autoSteve** [comment] 2024-11-20 21:29
It'd be great to understand how. Maybe a manual install in a different directory. I'll try it when I get a mo.

**Comment by autoSteve** [comment] 2024-11-21 07:44
> Someone mentioned on the community forum that they ended up with both oziee and bjreplay installed, and asked for assistance a couple of days ago.

It is not possible to set up two Solcast integrations bearing the same domain. Ozzie checked for that, and we check for that. If the manifest domain were changed however... Maybe. Not tried.

I tried having another `custom_components` folder `solcast_solar_old` containing 4.0.23 and it did nothing. HA chose 4.2.6. Tried calling the interloper `aolcast_solar`, wondering whether it was an alphabetic load thing. HA chose 4.2.6.

So the integration entry must point at the installed folder, ignoring the rest.

Ergo, if an install to a folder named other than `solcast_solar` had been done then its entry would do the same thing. It would ignore `solcast_solar` as the interloper.

When you remove a configured HACS repo it does not remove an integration folder. If you then remove the integration, the folder remains. You can re-add it, so removing repo in HACS just makes it unmanageable. I assume no upgrades will then be offered.

I then renamed the "orphaned" `solcast_solar` to `solcast_old`, manually put 4.0.23 in it and rebooted the entire VM. Tried to set up Solcast and it bombed with an exception. 4.0.23 is way too old it would seem, but it pre-dates me getting my grubby hands all over the code, and most closely resembles Oziee's last efforts.

And that begs the question, "How is Oziee's code even running?" Maybe I did something stupid with that test.

My next step would have been to set up BJ in HACS, download from there and see where things went.

I have been foiled for now.

**Closed** 2024-11-21 12:27 UTC
Labels: most odd
