### ISSUE TITLE
After V4.2.5 -> V4.2.6 upgrade - API Keys with non-alpha, non-numeric characters result in inability to edit configuration.

### ISSUE THREAD

**Issue by kaz911** [BJReplay/ha-solcast-solar#220] opened 2024-11-23 09:54 UTC
# Note to other Solcast Users from @BJReplay - if you land here having upgraded to v4.2.6 and having found you can't edit your integration configuration, and find this issue, please **downgrade to v4.2.5**, or if you have no urgent need to edit your configuration, please wait until v4.2.7.

Please see the note on the release notes for v4.2.6 https://github.com/BJReplay/ha-solcast-solar/releases/tag/v4.2.6

It wasn't clear on first release, and it was only just updated to make it clear that any non-alpha, non-numeric character causes a problem (it used to just warn about hyphens - but we've just had a user who knew they had a hyphen complain that they couldn't edit their configuration because they had a hyphen **and an underscore**) so from this point on, you've been warned.

## Describe the bug

After V4.2.5 -> V4.2.6 upgrade - modifying configuration generates error "API key contains invalid character" 

## To Reproduce

Edit the Solarcast Solar Service via the "Configure" 
Change something on the page 
Click "Submit"

and error "API key contains invalid character" pop up.

## Expected behavior

Configuration should be saved ;) 

## Screenshots

![image](https://github.com/user-attachments/assets/97ee4923-84a1-45c8-8f92-c964ac36dd10)

## Logs

I confirm:

- [ ] I have attached **debug** logs
- [ ] I have embedded **debug** logs in the issue description (enclosed in tick marks ``` for proper formatting)
- [x ] Confirmed **debug** logs are not required for this issue

Make sure you include logs from HA listing the output from the Solcast integration showing the error - this is particularly useful in debugging issues and helping to determine whether the issue is with the integration or the Solcast service

To add detailed debug information, add the following to your configuration.yaml and restart HA:

``` yaml
logger:
  default: warn
  logs:
    custom_components.solcast_solar: debug
```

To inspect and collect debug logs examine `/config/home-assistant.log` using File Editor or Visual Studio Code Server.

If you are using docker, it sometimes can be easier to gather logs using `docker compose logs -n 500 -f homeassistant` or similar

## Solcast Integration Version

- Integration Version [e.g. 4.0.29]

**Comment by BJReplay** [comment] 2024-11-23 10:08
No, it doesn't.

If I
- Edit the Solarcast Solar Service via the "Configure"
- Change something on the page
- Click "Submit"

It says:

![image](https://github.com/user-attachments/assets/26319b46-7238-4761-98ff-03298554928d)

However, if I deliberately put an invalid character into the API Key like so:

![image](https://github.com/user-attachments/assets/0974f8da-4587-439c-8bd3-f59a82249a10)

By copying and pasting an invisible invalid character

I can reproduce your problem:

![image](https://github.com/user-attachments/assets/969de3fd-d15c-4499-8c17-19f804ca5fee)

What that means is that you've got an invalid character in your API Key.

Not sure how it got there, but I imagine it got there accidently while you were trying to edit something else.

I'd suggest that you copy and paste your API key from your solcast toolkit (https://toolkit.solcast.com.au/) and you'll no longer have an invalid character.

**Comment by BJReplay** [comment] 2024-11-23 10:15
Closing issue: validation correctly reports if invalid characters are in the API Key field.  How they got there is a question for another day.  Cosmic Rays or Keyboard Issues are most likely.  Solution is re-pasting API Key.  Won't Fix.

**Comment by kaz911** [comment] 2024-11-23 10:15
I DID copy it again from SolarCast with NO change in behaviour. 

I have also tried to REMOVE the service - and add it again - with same problem

**Comment by autoSteve** [comment] 2024-11-23 10:16
This is interesting indeed. This is the test: `re.match("^[a-zA-Z0-9,]+$"`. Does the API key match this test using regex101.com? Is your key special in some way when you consder the test?

**Comment by BJReplay** [comment] 2024-11-23 10:20
> I have also tried to REMOVE the service - and add it again - with same problem

Are you sure that you're not putting in your Resource ID 
![image](https://github.com/user-attachments/assets/9dae10bd-1314-49c9-b680-9949092a6fa6)

Screen shots with partial redaction of your key would help, here.

More information would help, too.

Did the service work after the upgrade, and only stop after you tried to reconfigure it?

Is your API Key anything other than letters and numbers?

**Comment by kaz911** [comment] 2024-11-23 10:23
My API has a DASH in the middle 

(7Ge0rGHXXXMvILNh6sYmm-mFCbkWXXXX)  (replaced a few char's with XXXX's)

**Comment by autoSteve** [comment] 2024-11-23 10:26
That'll do it.

If you're up for it, change line 182 in `config_flow.py` to read this and report back after a reload.

```
                if not re.match("^[a-zA-Z0-9,\-]+$", api_key):
```

**Comment by kaz911** [comment] 2024-11-23 10:27
I don't know if the initial setup I did on previous version ignored the reg ex validation? But it worked until I upgraded to V4.2.6

I'll try and figure out where that is - It is my first Home Assistant setup - so i'm working my way through it.

**Comment by autoSteve** [comment] 2024-11-23 10:28
`/config/custom_components/solcast_solar`

**Comment by BJReplay** [comment] 2024-11-23 10:33
> I don't know if the initial setup I did on previous version ignored the reg ex validation? But it worked until I upgraded to V4.2.6

No, it's this version.  It added validation (because people were putting their Resource IDs into the API key field.

There are two options:  Downgrade to version 4.2.5, or remove the offending line.

@autoSteve has suggested the line to edit above - you'll need to edit that line (which you'll find in config_flow.py in /config/custom_components/solcast_solar

Or, if you want to downgrade, you can do that via HACS, too:

Go to HACS where you downloaded this, click on Solcast PV Forecast, 
![image](https://github.com/user-attachments/assets/dd7350b0-6d65-4e63-b2b2-631a7c67b499)

and click on redownload

![image](https://github.com/user-attachments/assets/d343a210-3a78-44b4-b42c-464a6aac723b)

When you get the option to choose which version:

![image](https://github.com/user-attachments/assets/ee274f3a-c21b-4568-b860-91891228900d)

Choose 4.2.5

![image](https://github.com/user-attachments/assets/3b356425-9712-4f44-bdf5-f6a6522acd41)

**Comment by BJReplay** [comment] 2024-11-23 10:41
Or, finally, @kaz911, if you're happy with the configuration, you don't actually need to downgrade or edit any files.  4.2.5 and 4.2.6 are functionally the same.

Obviously, if need to change the config, then you need to make a choice, but if you were just fiddling around and don't desperately need to change any config, sit tight, and the next version will fix things.  Your system is still running, you just can't save the config for the moment.

Sorry about blaming you for not attempting the obvious things like cutting and pasting your API key into the field - but if you don't say you've tried that, then that's the assumption when I can reproduce the error by including invalid characters and remove them by replacing the entire contents of the field.

**Comment by autoSteve** [comment] 2024-11-23 10:55
I have run this up in the simulator using an API key of aaaa-aaaa. The change works.

The change sucks, because it will not pick up (in its current form) that a resource ID has been used instead. This can be fixed, but is not simply fixed.

**Comment by kaz911** [comment] 2024-11-23 11:04
The resource ID's are 4 chars with "-"'s  * 4 - that should not be hard to match  - match on total string length and containing 4 dashes. 

API string length seems a lot longer.

**Comment by kaz911** [comment] 2024-11-23 11:05
> Or, finally, @kaz911, if you're happy with the configuration, you don't actually need to downgrade or edit any files. 4.2.5 and 4.2.6 are functionally the same.
> 
> Obviously, if need to change the config, then you need to make a choice, but if you were just fiddling around and don't desperately need to change any config, sit tight, and the next version will fix things. Your system is still running, you just can't save the config for the moment.
> 
> Sorry about blaming you for not attempting the obvious things like cutting and pasting your API key into the field - but if you don't say you've tried that, then that's the assumption when I can reproduce the error by including invalid characters and remove them by replacing the entire contents of the field.

I got it working again with ^[a-zA-Z0-9\-,]+$

And don't worry - I just appreciate you do the work !

I had a manual grabber collecting Solarcast before - so this is much better :)

/k

**Comment by autoSteve** [comment] 2024-11-23 11:22
Thanks for validating, @kaz911. The full fix is in PR #220, which also checks for using site-ID (🤦🏻) instead of API key.

And welcome to the integration!

**Comment by kodifan** [comment] 2024-11-24 14:28
still not working for free account on solcast.com.
every api key that is generated contains underscore "_"
i had to manually edit config_flow.py file  :
```
re.match("^[a-zA-Z0-9\-_,]+$", api_key)
```
to make it work

**Comment by autoSteve** [comment] 2024-11-24 14:49
Very interesting, @kodifan. I shall incorporate that in post-v4.2.6. Thanks for reporting!

These API keys are interesting creatures...

**Comment by autoSteve** [comment] 2024-11-24 15:27
In post-v4.2.6 the proposal is to remove validation of the key in favour of validating that it _does not_ exactly match the format of a site ID (xxxx-xxxx-xxxx-xxxx).

It has transpired that hyphens are a thing with API key. Underscores as well. What else? Post v4.2.6 it will not matter, just that it does not look like a well-formed site ID. (And it better not ever contain a comma, which I can confidently say it does not or folks would have hit issue long ago...)

**Comment by dafunkmaster** [comment] 2024-11-24 19:26
Very new to all of this, so not entirely sure what I am doing, but I can confirm that my API key has a - in it and I keep getting that error.

I've tried changing that line 182, but it's not working for me ... have tried a restart too, didn't fix it.

**Comment by autoSteve** [comment] 2024-11-24 22:46
> So I downgraded to 4.2.5 and then set the key and then upgraded to 4.2.6

And then what happened, @dafunkmaster?

You did the right thing by downgrading. Unless you are hitting one of the issues mentioned in the release notes and need it fixed, wait until v4.2.7. Or if the result of your trailed-off sentence was that all now works, then good on you.

**Comment by dafunkmaster** [comment] 2024-11-25 08:05
So downgrading to 4.2.5 allowed me to configure the API key and then
configured what I needed too.

I then upgraded to 4.2.6 and it was still working.

**Comment by tomatensaus** [comment] 2024-11-27 06:22
I still had the previous unmaintained integration, decided to remove it and install this one. Getting the same message.

My api key contains a "-" 
I also tried to install 4.2.5. I was able to configure it with my API key. 
Then proceeded to upgrade to 4.2.6

Checked and the integration is working now

**Comment by Oli-BY** [comment] 2024-11-30 15:03
4.2.5 works. After update to 4.2.6 its not working

**Comment by autoSteve** [comment] 2024-11-30 15:39
> 4.2.5 works. After update to 4.2.6 its not working. Its not possbile to save a new configuration.

Thanks, @Oli-BY.

But one-line issue reports do not help anyone, least of all yourself. Is this the same issue? Dunno. My crystal ball broke several issues ago...

Does your API key contain a hypen? Or some kind of Egyptian glyph? Or a smiley emoji?

**Comment by Oli-BY** [comment] 2024-11-30 18:07
> > 4.2.5 works. After update to 4.2.6 its not working. Its not possbile to save a new configuration.
> 
> Thanks, @Oli-BY.
> 
> But one-line issue reports do not help anyone, least of all yourself. Is this the same issue? Dunno. My crystal ball broke several issues ago...
> 
> Does your API key contain a hypen? Or some kind of Egyptian glyph? Or a smiley emoji?

Sorry for my imprecise description of my problem.
My API key contains a "_" (underscore?).
I get the error message "API key contains invalid character".

**Comment by Oli-BY** [comment] 2024-11-30 18:13
> I still had the previous unmaintained integration, decided to remove it and install this one. Getting the same message.
> 
> My api key contains a "-" I also tried to install 4.2.5. I was able to configure it with my API key. Then proceeded to upgrade to 4.2.6
> 
> Checked and the integration is working now

is it a "-" or a "_" ?

**Comment by BJReplay** [comment] 2024-12-01 10:58
I am going to lock this issue to existing participants, because it is attracting "me too" comments that really don't help anyone.

I'm also going to make it even clearer on the release that if your API key has anything other than letters and numbers, don't install 4.2.6.  I know that will reset the download stats, @autoSteve, but as TISM said: "I've lost interest".  I think it's more important to at least have a warning that people haven't read that is accurate, than an inaccurate, somewhat misleading warning (that people still ignore - as evidenced above).

267 + 3458, before resetting the count :)

**Closed** 2024-12-02 06:21 UTC
Labels: bug
