### ISSUE TITLE
Zeroing last pv_estimate in solcast_api.SolcastApi.makeenergydict

### ISSUE THREAD

**Issue by rotgier** [BJReplay/ha-solcast-solar#175] opened 2024-09-25 12:57 UTC
### The problem

I was browsing the code of this integration to understand how data from solcast is made available in my HA and I've noticed that a part of this commit does not seem to be needed:

https://github.com/BJReplay/ha-solcast-solar/commit/c672e2f1f12abbce29d613d79886d642afcf71b1#diff-1def68845dd45333941984fa12ec6a849c48bc8762d7a98eeb9ba06e28113bb6R635

I am referring to this part of the above commit:
![image](https://github.com/user-attachments/assets/1eeacabc-c089-4853-a45d-34575edc14b4)

Why should the last value before "0.0" be zeroed?

Also I would make this method simpler:

```
Index: custom_components/solcast_solar/solcastapi.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/custom_components/solcast_solar/solcastapi.py b/custom_components/solcast_solar/solcastapi.py
--- a/custom_components/solcast_solar/solcastapi.py	(revision 3bfbd259b16009d799389958a5fc7cbf592bfa82)
+++ b/custom_components/solcast_solar/solcastapi.py	(date 1727182051413)
@@ -1540,20 +1540,17 @@
             lastk = -1
             for v in self._data_forecasts:
                 d = v['period_start'].isoformat()
-                if v[self._use_data_field] == 0.0:
+                value = v[self._use_data_field]
+                if value == 0.0:
                     if lastv > 0.0:
-                        wh_hours[d] = round(v[self._use_data_field] * 500,0)
-                        wh_hours[lastk] = 0.0
-                    lastk = d
-                    lastv = v[self._use_data_field]
+                        wh_hours[d] = 0.0
                 else:
+                    wh_hours[d] = round(value * 500, 0)
                     if lastv == 0.0:
-                        wh_hours[lastk] = round(lastv * 500,0)
-
-                    wh_hours[d] = round(v[self._use_data_field] * 500,0)
+                        wh_hours[lastk] = 0.0
 
-                    lastk = d
-                    lastv = v[self._use_data_field]
+                lastk = d
+                lastv = value
         except:
             _LOGGER.error("Exception in makeenergydict(): %s", traceback.format_exc())
 

```

We only need to:
- forget all zero values which are followed by another zero value AND preceded by yet another zero value

We should NOT forget a zero value:
- followed by a non-zero value
- preceded by a non-zero value

I hope this make sense :)

### What version of Solcast Integration has the issue?

v4.1.7

### What version of Home Assistant are you using?

haos

### Diagnostics information

final code:

```
    def makeenergydict(self) -> dict:
        """Make an energy-compatible dictionary."""
        wh_hours = {}
        try:
            lastv = -1
            lastk = -1
            for v in self._data_forecasts:
                d = v['period_start'].isoformat()
                value = v[self._use_data_field]
                if value == 0.0:
                    if lastv > 0.0:
                        wh_hours[d] = 0.0
                else:
                    wh_hours[d] = round(value * 500, 0)
                    if lastv == 0.0:
                        wh_hours[lastk] = 0.0

                lastk = d
                lastv = value
        except:
            _LOGGER.error("Exception in makeenergydict(): %s", traceback.format_exc())

        return wh_hours
[Simplified_method.patch](https://github.com/user-attachments/files/17131170/Simplified_method.patch)

```

### Logs debug/info/error output

```txt
No debug info but from code analysis I see that the last non-zero period_start will be forgotten ;). And this is a small bug.
```

**Comment by BJReplay** [comment] 2024-09-25 23:57
The commit you linked to is a year old, before I took on looking after this project, and is to the entire commit, so it's really confusing to try to see what you're asking about. 

That said, eyeballing the code you've pasted, I don't think you've got this right.  It's not forgetting a value; it's filling in a blank between values.

If you have a proposed change:
- Are you running it?
- Is it producing identical forecasts in your instance of HA?
- If so, please fork this repo and submit a PR, and we'll be more than happy to consider it where we can better use the tools that gitbub provides to review proposed PRs 😉

**Comment by BJReplay** [comment] 2024-09-27 00:42
@autoSteve Now that I've read this again, I see that there is an actual code improvement, and a question.

The code improvement doesn't actually implement the implied suggestion (removing ("forgetting" in the language of the issue) setting the last value to zero if the current value is zero), so is reasonable.

I'm going to suggest we include it in the draft v4.1.8.

What's more, I think the `if lastv == 0.0:` in the `else:` leg might be redundant: the previous run through the dictionary should have already set `wh_hours[d]` in that iteration to 0.0

@rotgier the explanation appears to be that the process of building the energy-compatible dictionary is that for transitions from to zero (`v[self._use_data_field] == 0.0` **and,** `lastv > 0.0` this routine sets the previous value to zero as well `wh_hours[lastk] = 0.0`

It is not forgetting values - that would be leaving them out of the dictionary.  It is setting them to zero (though, perhaps, that is what you meant).

My **guess** is that it is doing it so that the display of the forecast line on the energy dashboard looks better.

**Comment by BJReplay** [comment] 2024-09-27 01:02
Steve, I'd propose a change to your working copy, but I can't, and I don't want to risk creating an Einstein-Rosen bridge by forking your repo to produce a PR to your branch 🤣

So, here's what I'd do:

```
    def __make_energy_dict(self) -> dict:
        """Make a Home Assistant energy dashboard compatible dictionary.

        Returns:
            (dict): An energy dashboard compatible data structure.
        """
        wh_hours = {}
        try:
            lastv = -1
            lastk = -1
            for v in self._data_forecasts:
                d = v['period_start'].isoformat()
                value = v[self._use_data_field]
                if value == 0.0:
                    if lastv > 0.0:
                        wh_hours[d] = 0.0
                        wh_hours[lastk] = 0.0
                else:
                    wh_hours[d] = round(value * 500,0)

                lastk = d
                lastv = value
        except:
            _LOGGER.error("Exception in __make_energy_dict(): %s", traceback.format_exc())

        return wh_hours
```
This preserves the reason unknown logic for zeroing the last entry if the current entry is now zero, as well as (even though it wasn't as clear) writing a rounded, multiplied by 500 zero to the current entry for zero values). 

If not zero, it now writes a converted to Wh value only, and doesn't faff around writing a rounded, converted to Wh version of zero for the previous value, since that was done last time.


As you can see
```
                     if lastv == 0.0:
                        wh_hours[lastk] = round(lastv * 500,0)
```
is completely removed from the else leg.  If lastv was zero, then wh_hours(lastk) was already set to zero.  Setting it again would be pointless.

**Comment by autoSteve** [comment] 2024-09-27 01:09
In the words of @BJReplay, "Are you running it, @BJReplay?"

> Einstein-Rosen bridge

😂😂😂 Yeah, don't poke the GitHub gods.

**Comment by BJReplay** [comment] 2024-09-27 01:12
> In the words of @BJReplay, "Are you running it, @BJReplay?"

Fair question!  I am literally editing my local solcastapi.py as we speak!  Stand by for notes!

**Comment by BJReplay** [comment] 2024-09-27 01:24
Yeah, not quite right 🤣🤣🤣
![image](https://github.com/user-attachments/assets/6b9a3079-779e-4d94-9b64-d82c232044cb)
Maybe that if is required after all!
I hate python tabs vs spaces sensitivity when editing in place.  That took far longer than it should have.

**Comment by BJReplay** [comment] 2024-09-27 01:55
Code Running:

```
    def __make_energy_dict(self) -> dict:
        """Make a Home Assistant energy dashboard compatible dictionary.

        Returns:
            (dict): An energy dashboard compatible data structure.
        """
        wh_hours = {}
        try:
            lastv = -1
            lastk = -1
            for v in self._data_forecasts:
                d = v['period_start'].isoformat()
                value = v[self._use_data_field]
                if value == 0.0:
                    if lastv > 0.0:
                        wh_hours[d] = 0.0
                        wh_hours[lastk] = 0.0
                else:
                    if lastv == 0.0:
                        wh_hours[lastk] = 0.0
                    wh_hours[d] = round(value * 500,0)

                lastk = d
                lastv = value
        except:
            _LOGGER.error("Exception in __make_energy_dict(): %s", traceback.format_exc())

        return wh_hours
```

Shape Produced:

![image](https://github.com/user-attachments/assets/8b1d7cff-fcc4-40ac-baaa-54375b5a34d2)

Note the order of operations is apparently important - this:

```
                    wh_hours[d] = round(value * 500,0)
                    if lastv == 0.0:
                        wh_hours[lastk] = 0.0

```
produces this:

![image](https://github.com/user-attachments/assets/0674d541-78db-4b08-b4ce-806c05c57ea8)

Oziee might have spent some time tweaking the shape :)

**Comment by autoSteve** [comment] 2024-09-27 02:03
That's confirmed, @BJReplay.

**Comment by BJReplay** [comment] 2024-09-27 03:17
@rotgier FYI we've taken part of your suggestion on board, but if you play with your suggestion on your HA instance, you'll no doubt see that the form of the forecast isn't ideal.

Will be fixed in upcoming v4.1.8 pre-release.  You may want to consider enabling access to pre-releases for this integration if you're interested in testing the code that has resulted from your suggestion.  Or not. You choose 🤣

See https://github.com/BJReplay/ha-solcast-solar/discussions/148 for information on how to enable access to pre-releases under HACS 2.0.

**Comment by rotgier** [comment] 2024-09-27 09:32
> It is not forgetting values - that would be leaving them out of the dictionary. It is setting them to zero (though, perhaps, that is what you meant).

Yes, leaving the last value out is what I meant by forgetting 

This should not be zero
![image](https://github.com/user-attachments/assets/55dd5e00-aeb9-4a3a-8bc3-d2868bd991be)

Because I should get sun power after 18:00 ;)

![image](https://github.com/user-attachments/assets/735b2dcb-0172-4102-bcb3-f7a0a649a4b6)

(above datetimes are in UTC and I'm in UTC+2)

So definitely the value is forgotten 😎 

So maybe this "if" is needed for something else, but we've still have the problem of "forgetting" (in the language of the issues 🙃 ).


Let me quickly dive once again into the code 🤿

**Comment by rotgier** [comment] 2024-09-27 09:47
Ok, so when I've changed the code to the snippet that I've proposed:

![image](https://github.com/user-attachments/assets/487cce5f-ecb6-48b6-8245-fc70b5e8c45e)

The problem of forgotten value is solved:

![image](https://github.com/user-attachments/assets/3fe70af8-3178-4750-a29e-0fd7f88a2b10)


So my code wins 🤠  .... just kidding.

To be honest I'm not sure why you've got this strange behavior.

Maybe if you could send solcast.json then we could investigate what is going on. (I can also send mine)

> Note the order of operations is apparently important

This is not possible unless "period_start" entries are duplicated in your solcast.json ;)

**Comment by BJReplay** [comment] 2024-09-27 09:59
Well, we don't accept PRs in the form of screen shots, sorry 🤣.

You can see (as this issue is referenced in the PR) what we're going to include in v4.1.8: https://github.com/BJReplay/ha-solcast-solar/pull/165/commits/332e72176b845e17ec0997d6a5af98e7e793c4f9.

Try it.

See if you like it.

If you don't, submit a PR which we'll review.

Or just clone the repo and run your own version :)

What I found leaving out the "forgetting" is a badly shaped start and/or end of the forecast curve.

Remember, the change doesn't impact the reported figures for any of the Solcast Sensors, just the figures used to shape that forecast line.

The "forgetting" smooths the ramp up / ramp down at the edge of the curve.

**Comment by autoSteve** [comment] 2024-09-27 10:12
So...

The proposal, correct me if I'm wrong, @rotgier is this (commented line).

``` python
    def __make_energy_dict(self) -> dict:
        """Make a Home Assistant energy dashboard compatible dictionary.

        Returns:
            (dict): An energy dashboard compatible data structure.
        """
        wh_hours = {}
        try:
            lastv = -1
            lastk = -1
            for v in self._data_forecasts:
                d = v['period_start'].isoformat()
                value = v[self._use_data_field]
                if value == 0.0:
                    if lastv > 0.0:
                        wh_hours[d] = 0.0
                        # wh_hours[lastk] = 0.0 <-- This line right here...
                else:
                    if lastv == 0.0:
                        wh_hours[lastk] = 0.0
                    wh_hours[d] = round(value * 500, 0)

                lastk = d
                lastv = value
        except:
            _LOGGER.error("Exception in __make_energy_dict(): %s", traceback.format_exc())

        return wh_hours
```

Resulting in something like this, with the last day value being 0.1kWh in my case, and not zero, yes?.

<img width="1004" alt="image" src="https://github.com/user-attachments/assets/03156c4c-1c83-4a0b-a84a-22bdc17334d7">

Correct?

**Comment by rotgier** [comment] 2024-09-27 10:14
> Well, we don't accept PRs in the form of screen shots, sorry 🤣.

Oh come on. You've got OCR and Chat GPT 🙃 

Send me your solcast.json and I will make my proposal in the PR you are pointing to which works both for me and for you 👍

**Comment by autoSteve** [comment] 2024-09-27 10:19
Maybe it's not. I get the same result with or without that line.

<img width="445" alt="image" src="https://github.com/user-attachments/assets/c039edea-2542-4ffb-9586-b3549b7661fb">

**Comment by rotgier** [comment] 2024-09-27 10:19
> So...
> 
> The proposal, correct me if I'm wrong, @rotgier is this (commented line).
> 
> ```python
>     def __make_energy_dict(self) -> dict:
>         """Make a Home Assistant energy dashboard compatible dictionary.
> 
>         Returns:
>             (dict): An energy dashboard compatible data structure.
>         """
>         wh_hours = {}
>         try:
>             lastv = -1
>             lastk = -1
>             for v in self._data_forecasts:
>                 d = v['period_start'].isoformat()
>                 value = v[self._use_data_field]
>                 if value == 0.0:
>                     if lastv > 0.0:
>                         wh_hours[d] = 0.0
>                         # wh_hours[lastk] = 0.0 <-- This line right here...
>                 else:
>                     if lastv == 0.0:
>                         wh_hours[lastk] = 0.0
>                     wh_hours[d] = round(value * 500, 0)
> 
>                 lastk = d
>                 lastv = value
>         except:
>             _LOGGER.error("Exception in __make_energy_dict(): %s", traceback.format_exc())
> 
>         return wh_hours
> ```
> 
> Resulting in something like this, with the last day value being 0.1kWh in my case, and not zero, yes?.
> 
> <img alt="image" width="1004" src="https://private-user-images.githubusercontent.com/37229860/371489765-03156c4c-1c83-4a0b-a84a-22bdc17334d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MzIyNjEsIm5iZiI6MTcyNzQzMTk2MSwicGF0aCI6Ii8zNzIyOTg2MC8zNzE0ODk3NjUtMDMxNTZjNGMtMWM4My00YTBiLWE4NGEtMjJiZGMxNzMzNGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDEwMTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNDNmYmMxNmY5ZTg0OGZkMDM3NGE2ZDQyNDRhMjkxN2ZkMTI5YjllNjM2OWVmZmUwNDYzYmQwOTViMmYzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Gvzv1L3wq_Ru6rKbRj3D45iirUPXIcJ0Cg9seDAJ3s0">
> Correct?

Yes, correct 👍 

But instead:

```
                    if lastv == 0.0:
                        wh_hours[lastk] = 0.0
                    wh_hours[d] = round(value * 500, 0)
```

I've got the order changed (which makes more logical sense IMHO)

```
                    wh_hours[d] = round(value * 500, 0)
                    if lastv == 0.0:
                        wh_hours[lastk] = 0.0
```

I see that it also works fine for you @autoSteve . 

I'm not sure why @BJReplay has some strange behaviour on graphs with my ... oh so perfect ... code screenshot 😇 .

Again having some solcast.json fragment which causes these problems could be beneficial.

**Comment by rotgier** [comment] 2024-09-27 10:24
The proper way of dealing with this would be a nice pytest, which provides given solcast.json (or several samples) and asserts data returned by `makeenergydict` 💪

**Comment by BJReplay** [comment] 2024-09-27 10:25
> Again having some solcast.json fragment which causes these problems could be beneficial.

Again, it's not the solcast.json fragment that is the problem.  Read up the comments already made issue, and you can see - since I've pasted screenshots, which are apparently your preferred method of communication https://github.com/BJReplay/ha-solcast-solar/issues/175#issuecomment-2378252278 what happens when the order is reversed.

Now, perhaps it is down to me editing in place and restarting HA and me running core in docker.

I don't know.

But, to be honest, as the repo owner, I don't give a 💩 what order the lines are, as they both get executed.

But what I do care about is the left-hand side of the graph.  If you leave out some of those forgettings, you get [this](https://github.com/BJReplay/ha-solcast-solar/issues/175#issuecomment-2378225730)

The proper way of dealing with this would be for you to raise a PR with examples.  Since you've suggested the proper way, why don't you get of your high horse and do it, instead of instructing others on how to do it.

**Comment by autoSteve** [comment] 2024-09-27 10:26
Righto @rotgier.

Nope. This will not be merged as is. @BJReplay and I both hit this oddity.

<img width="899" alt="image" src="https://github.com/user-attachments/assets/eea2a3b7-7667-4955-8181-aab623a4bfdd">

**Comment by BJReplay** [comment] 2024-09-27 10:28
> Nope. This will not be merged as is. @BJReplay and I both hit this oddity.

No Shit, Sherlock (not you @autoSteve , @rotgier, who doesn't understand that you can add two points to a dictionary with the same key and two different values, and HA will render them both on the Energy Dashboard, **regardless** of what you have in your solcast.json)

**Comment by rotgier** [comment] 2024-09-27 10:30
Guys, you're right 👍 . However it would be hard for me to fix If I cannot replicate it in my environment.

**Comment by BJReplay** [comment] 2024-09-27 10:33
The forgetting is there so that the forecast starts and ends on zero and looks more like a bell curve.  The previous owner of this repo (rest his github soul) didn't want the forecast line hanging in the air at either end and this was his solution, and apart from the fact that there were some redundant repeated lines of code - **now removed** - his solution works.

We've wasted enough time discussing it.

I'm closing this now (given that there is a fix in a PR waiting to be merged).

**Closed by BJReplay** 2024-09-27 10:33 UTC
Labels: question, distraction, suggestion
