### ISSUE TITLE
Pre Release 4.1.4 fails to load with Exception

### ISSUE THREAD

**Issue by sh00t2kill** [BJReplay/ha-solcast-solar#153] opened 2024-09-02 00:40 UTC
**Describe the bug**

**To Reproduce**
Update to 4.1.4 and restart HA.
The integration throws an exception.

**Expected behavior**
The integration should start.

**Screenshots**
N/A

**Logs**

```
Exception in load_saved_data(): Tracebak (most recent call last):
File "/config/custom_components/solcast_solar/solcastapi.py". line 559. in load_saved_data
  for a, _api_key in ks:
  
  ValueError: too many values to unpack (expected 2)
  ```
**Solcast Integration Version**
 - 4.1.4

**Comment by BJReplay** [comment] 2024-09-02 01:11
Can you turn on debugging for the integration, and restart HA, or post full logs if you have them.

It looks like your solcast-sites.json might have been corrupted.  Have a look at it, perhaps post it here, but redact your lat and longitude.

**Comment by dwheaton-paloit** [comment] 2024-09-02 01:23
I was on  pretty old version. Maybe 4.0.26 or so.

4.1.4 throw the error above.
I rolled back to 4.1.3 and it worked.

I updated to 4.1.4, and its now working.

I will do a fresh install on my non prod HA environment and see if i can replicate the error.

**Comment by sh00t2kill** [comment] 2024-09-02 01:24
I was on pretty old version. Maybe 4.0.31 or so.

4.1.4 throw the error above.
I rolled back to 4.1.3 and it worked.

I updated to 4.1.4, and its now working.

I will do a fresh install on my non prod HA environment and see if i can replicate the error.

**Comment by autoSteve** [comment] 2024-09-02 01:58
That section of code executed because the integration thought that a new API key had been added.

If you could please describe your set-up it might help to visualise what happened. One API key or two? Number of sites? Is there anything unusual with how the API key is specified in configuration? Did you add an API key?

**Comment by sh00t2kill** [comment] 2024-09-02 02:01
One site, one API key. Theres nothing unsual that im aware of.
I didnt change any of the existing configuration, just updated the integration.

As I mentioned, its no longer an actual issue for me, as i can no longer replicate it in production.

**Comment by BJReplay** [comment] 2024-09-02 02:18
> As I mentioned, its no longer an actual issue for me, as i can no longer replicate it in production.

OK, thanks.

I wonder if there was a potential breakage that might occur if someone was stuck on a really old version, and jumped from say 4.0.31 straight to 4.0.14.

There are still roughly 500 more downloads of 4.0.31 than 4.1.13.

But even so, I'd be more inclined to blame gremlins that thought there was a change to API keys when there wasn't (because that code should have also fired in 4.1.13) than anything else.

**Comment by sh00t2kill** [comment] 2024-09-02 02:36
I thought it might be some weird migration thing too.

Will try and replicate it.

**Comment by autoSteve** [comment] 2024-09-02 07:15
Thanks for hitting this, @sh00t2kill. Had that code actually succeeded then two API calls would have been used up getting the forecast for a "new" site, along with the site forecast history. I assume it is not a new site in this case.

This code was broken:

```
559:                                for a, _api_key in ks:
```

It should be:

```
559:                                for a, _api_key in ks.items():
```

I am convinced that there is a sleeping issue here, @BJReplay, as it sounds like @sh00t2kill has had the same site configured for ages.

That code is fed by the following, which looks fine. (That `d.get('resource_id', '')` happens makes my eye twitch because no further checks, but that is what it is.)

```
                            # Check for any new API keys so no sites data yet for those
                            ks = {}
                            for d in self.sites:
                                if not any(s == d.get('resource_id', '') for s in json_data['siteinfo']):
                                    ks[d.get('resource_id')] = d.get('apikey')
```

The `json_data` is the contents of the loaded `solcast.json` file. And `self.sites` is fed when the get sites API call or cache load happens.

In this case there were sites loaded from Solcast (or cache), but the supposed contents of the `solcast.json` file did not mention these sites, hence was about to do an integration site set-up (burning API calls in the process).

If the `solcast.json` could not be loaded then an entirely different code path would have been followed.

In this case the file existed, was successfully loaded, yet the site was not seen in the `json_data['siteinfo']` dictionary. The way the code is written, if the 'siteinfo' key does not exist an exception would have (reasonably) occurred, indicating that the contents in memory of `solcast.json` was actually of JSON format, and had something to work with.

If the API key had changed then this code path would have been followed, and would have been justified in getting sites forecast. If the site had been removed at Solcast.com then a new one created, equally so.

To answer the question about why downgrading then upgrading helped, the answer is because this Python coding error was introduced by me in v4.1.4, so great catch. When downgraded, this code path would have succeeded because API key/site ID changed, and then because no sites to update v4.1.4 would not have used this code path. Is that correct, @sh00t2kill? Site ID changed?

**Comment by sh00t2kill** [comment] 2024-09-02 08:01
It didn't change, but maybe the fact I was on such an old version (it may have been even older than 4.0.31, I can check a backup if that matters) then maybe the format of how it'd saved changed?

I haven't reconfigured in since the previous maintainer.

**Comment by BJReplay** [comment] 2024-09-02 08:06
> I haven't reconfigured in since the previous maintainer.

I've been able to repro the error message by adding a new site in the Solcast Website, where it picks up a new resource_id.

Is there any chance you did this - create a new version of your solar array in the Solcast Website, and deleted the old version any time in the last few months?

That may have been enough?

**Comment by sh00t2kill** [comment] 2024-09-02 08:09
Not that I recall. It's possible I logged in and made changes when the old integration stopped working, but I dont remember doing anything.

**Comment by autoSteve** [comment] 2024-09-02 08:10
The `solcast.json` schema has been the same since Oziee days, BTW. Still V4. So you'd need to have been on a v3.x, which is truly ancient.

**Comment by BJReplay** [comment] 2024-09-02 08:11
> It should be:
> 
> ```
> 559:                                for a, _api_key in ks.items():
> ```

Code on line 614 is still `for a, _api_key in ks:`
https://github.com/BJReplay/ha-solcast-solar/blob/Fix-usage-cache-timestamp/custom_components/solcast_solar/solcastapi.py#L614

Is that why I was able to repro by adding a new site?

**Comment by autoSteve** [comment] 2024-09-02 08:14
I can't help but think that this kind of event (had the exception _not_ been hit) be the cause of some folks losing their forecast history a while back. Circa v4.0.31...

I would _love_ to know what caused this code path to be run for you.

I would also _love_ to know whether you now have any history older than 14 days.

**Comment by BJReplay** [comment] 2024-09-02 08:22
_Adding this comment here (out of temporal sequence) after mistakenly adding it to the wrong issue earlier)_

This appears to be reproducible with a single API key, and with adding a second resource ID to the API Key.

I did this by adding a second micro array (1kW AC/DC) at the same location as my existing array).

This is the partially redacted content of solcast-sites.json at the time that the integration is failing to load:

`{"sites": [{"name": "BLAH", "resource_id": "3f77-9366-ebbc-b925", "capacity": 5, "capacity_dc": 4.85, "longitude": yada, "latitude": yada, "azimuth": -123, "tilt": 5, "install_date": "2012-04-18T14:00:00.0000000Z", "tags": ["Home ", "yada", "Flat Roof"]}, {"name": "BLAH 2.0", "resource_id": "3173-8af2-5d85-fae4", "capacity": 1, "capacity_dc": 1, "longitude": yada, "latitude": yada, "azimuth": 123, "tilt": 5, "install_date": "2001-12-31T13:00:00.0000000Z", "tags": ["Test"], "location": "yada, VIC Australia"}], "page_count": 1, "current_page": 1, "total_records": 2}`

Note that the first resource_id was the existing one, and the second resource_id was the newly added resource_id.

**Comment by sh00t2kill** [comment] 2024-09-02 08:22
I now only have the last few days of history. Unfortunately its only with the weather starting to warm up here, and I use forecast data to drive my pool heat pump automation, that i noticed it wasnt working.

I just checked a backup from this morning.
I was on 4.0.26, but i manually patched a fix that was an open PR on Oziee's repo, the one that fixed the json data issue, and then promptly forgot about it.

I hadnt even yet added this repo to HACS.

**Comment by BJReplay** [comment] 2024-09-02 08:25
> I now only have the last few days of history. Unfortunately its only with the weather starting to warm up here, and I use forecast data to drive my pool heat pump automation, that i noticed it wasnt working.

See [this discussion](https://github.com/BJReplay/ha-solcast-solar/discussions/49) and in particular [this post](https://github.com/BJReplay/ha-solcast-solar/discussions/49#discussioncomment-9992022) for information on how to recover your missing historical data.

**Comment by sh00t2kill** [comment] 2024-09-02 08:41
Thanks. I restored some. That was easier than expected.

**Comment by autoSteve** [comment] 2024-09-02 08:52
> I was on 4.0.26

4.0.26 was a BJReplay version (or possibly someone else's if you were doing other). Oziee committed GitHub self-harm 4.0.23 if memory serves, and I do not believe any Python changes happened in BJ 23->26. (Well done getting off that code. There were bear traps everywhere.)

~~My attitude to forecast history is that it is just a pleasing nice-to-have on a chart. Others disagree, for various reasons, but in my book knowing whether the bureau of meteorology got it right six months ago is of no interest. It's already happened. We know what the answer was.~~ (You are clearly in the latter camp, having restored. 😂)

It does worry me though, that forecast history can just get zapped because the integration thinks a site ID changed. It should not if it hasn't, and it should not burn through two API calls in doing the zapping. The schema is the same. That's why I'd love to know the circumstances of this issue report.

I reckon this is an older version to newer transition thing. Shouldn't be, but this is likely given history.

I really would not mind getting my grubby hands on your backup and upgrading it myself. Promise not to abuse your API key...

**Comment by autoSteve** [comment] 2024-09-02 09:20
> I will see if i can make that haystack smaller as now I am curious.

Just an FYI, @sh00t2kill, a while back someone mentioned that they had had history loss multiple times in the past, back in Oziee time, and seemingly for no reason. (Wasn't you was it?)

I thought this could be due to him changing the json file version. (That definitely does it, so 🤷‍♂️, but surely he would have mentioned those sorts of breaking changes in release notes, because folks raise issues and Oziee hated issues.) But it's been file V4 for ages now, and here we are. It was V4 for 4.0.22 and even earlier I believe, so that's not it.

It is highly likely that there is a hidden nasty. I have personnally touched nearly every line of code, especially the start-up stuff to implement back-off retries and haven't found it. I stared at code for days (literally) a while back looking for just this issue and expecting to find an answer. I didn't.

**Comment by BJReplay** [comment] 2024-09-02 10:10
FYI @sh00t2kill, I was able to repro your original error by changing my resource_id - the GUID-like ID assigned by Solcast when you create a PV system on their website.

Changing (or adding) a PV system caused 4.1.4 to choke a little.

I also lost forecast history before 27 August.

I've just tested the fix and it works, so you found a bug and we've fixed it - so thanks!

**Comment by sh00t2kill** [comment] 2024-09-02 10:14
I don't think my guid changed. I will double check.

**Comment by sh00t2kill** [comment] 2024-09-02 11:37
I checked a couple of random backups: the siteinfo GUID has *NOT* changed.

Whats potentially interesting is; when its failed, there is often an empty forecasts array.
I am taking a guess, but could an api failure or similar be trashing the historical data by replacing with an empty set?

**Comment by autoSteve** [comment] 2024-09-02 12:25
The comparison is to the data in the `solcast.json` cache and the `solcast-sites.json` cache/API result, and a mismatch causes action.

> when its failed, there is often an empty forecasts array

More information on this, please? Can't visualise.

**Comment by sh00t2kill** [comment] 2024-09-02 12:45
I went down the rabbit hole and wanted to see if i could find a pattern.
One thing i did find was a single case, around the time history data dissapeared, where solcast.json was literally just this:

```
{"siteinfo": {"xxxx-xxxx-xxxx-xxxx": {"forecasts": [] "tally": 0}}, "last_updated": "xxxx", "version": 4}
```

Probably some issue thats already been addressed, but i did notice that history dissapeared occasionally. One thing I didnt know, until this evening, was that it wasnt meant to!

**Comment by autoSteve** [comment] 2024-09-02 14:02
ALICE! DON'T GO!!! 🤣

That is a doozy. My mind is bent because ... can't even. Can't even think how that munted `solcast.json` could eventuate.

But it did.

This is a brilliant bit of info to naval gaze over. It's complete, but completely messed up.

Say "Hi" to the Mad Hatter from me.

**Comment by sh00t2kill** [comment] 2024-09-02 23:15
> The comparison is to the data in the `solcast.json` cache and the `solcast-sites.json` cache/API result, and a mismatch causes action.
> 

A thought occured overnight. The older versions dont *have* a `solcast-sites.json` file. Is that how i hit this path in the first place?

**Comment by sh00t2kill** [comment] 2024-09-03 01:11
I havent looked at the code, but was hypothesising that it was looking for info in that file, couldnt find it, and thats how that execution path got triggered. If i throw out enough ideas something might stick eventually.

**Comment by sh00t2kill** [comment] 2024-09-03 01:21
> ALICE! DON'T GO!!! 🤣
> 
> That is a doozy. My mind is bent because ... can't even. Can't even think how that munted `solcast.json` could eventuate.
> 
> But it did.
> 
> This is a brilliant bit of info to naval gaze over. It's complete, but completely messed up.
> 
> Say "Hi" to the Mad Hatter from me.

I vaguely remember trying to find the cause of it when it happened. It was a while ago though. Im guesing some sort of conneciton failure or exception blew away the data.

Is there a weird edge case where dopast is set to True by the http data call, and it shouldnt be?
or some other strange condition where _loaded_data attribute never gets set to True.
I cant see anything obvious, BUT, they look like the most obvious candidates.

**Comment by BJReplay** [comment] 2024-09-04 07:37
I'm going to close this issue, having opened #155 to track it with a reference back to the Eureka Comment given that the original issue has almost certainly been repro'd and closed now.

**Closed by BJReplay** 2024-09-04 07:37 UTC
