### ISSUE TITLE
Solcast PV - added as lovelace, not integration

### ISSUE THREAD

**Issue by DavidAntonin** [BJReplay/ha-solcast-solar#10] opened 2024-06-05 10:06 UTC
### The problem

I installed Solcast via HACS and instead of integrating it appeared in lovelace. So there is no Solcat device available either

### What version of Solcast Integration has the issue?

v4.0.25

### Logs debug/info/error output

```txt
it shows up in HACS in the lovelace tab
```

**Comment by paddawan2002** [comment] 2024-06-05 16:55
This occurred because you clicked on the "Open HACS Repository on My Home Assistant" link and it adds as a Lovelace or Plugin which means it doesn't show under integrations.

Remove the custom repository in HACS and re-add this GitHub repository URL manually but set it as an integration.

**Comment by mZ738** [comment] 2024-06-05 21:32
See comment above. 
Created a [PR](https://github.com/BJReplay/ha-solcast-solar/pull/11)

After removing the repo from your list, try this link.
https://my.home-assistant.io/redirect/hacs_repository/?owner=BJReplay&repository=ha-solcast-solar&category=integration.

**Comment by cromefire** [comment] 2024-06-05 21:35
Duplicate of #8

**Comment by BJReplay** [comment] 2024-06-05 23:37
Closed in PR#11

**Closed by BJReplay** 2024-06-05 23:37 UTC
